CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
id int AUTO_INCREMENT,
burger_name VARCHAR(100),
devoured BOOLEAN  NOT NULL DEFAULT 0,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);